development:
  adapter: postgresql
  encoding: utf8
  database: resizer_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: resizer_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: resizer_development
  host: localhost
  pool: 5

cucumber:
  <<: *TEST
